### ISSUE TITLE
Integrated type checks

### ISSUE THREAD

**Issue by patriksimek** [pekim/tedious#202]
There are situations when you accidentally pass a value that doesn't match specified data type, for example when you pass `999` to `TinyInt`. There are no type chcecks in Tedious so the application throws an `Out of bounds` error in Tedious core which also cause application to crash. Because of that, I suggest to add type checks.

This idea is based on https://github.com/patriksimek/node-mssql/issues/84 but I belive this feature should be implemented right in the Tedious core, not mssql.

Before I start working on this, I would like to discuss the feature design. There are two ways of how this can be done.

### Synchronous errors

```javascript
try {
	request.addParameter("name", TYPES.TinyInt, 999);
} catch (err) {
	err instanceof TypeError
	err.code === "ETYPE"
	err.message === "Value does not match the type of parameter 'name'."
}
```

### Asynchronous errors

```javascript
request = new Request('select @name', function(err) {
	err instanceof TypeError
	err.code === "ETYPE"
	err.message === "Value does not match the type of parameter 'name'."
});
request.addParameter("name", TYPES.TinyInt, 999);
connection.execSql(request);
```

I preffer the second one, but I would like you to tell me what suits your needs the best. I also count with an option to disable type checks.

**Comment by arthurschreiber** [comment]
Passing a wrong/out-of-bounds value to `request.addParameter` should cause an `Error` to be thrown right there, not later when the request is executed. It is a programmer error and happens when executing a fully synchronous function, making this an async error does not seem "correct" to me.

**Comment by bretcope** [comment]
It's a matter of mixing error handling strategies. While we certainly _could_ give an earlier error in the form of an exception, it means there is more than one place to check for an error. There is _always_ going to be a callback which receives an error argument, and users are well accustomed to checking it.  There is almost never going to be a try/catch around it because that's not the error handling strategy in most node.js libraries which involve async.

I don't see any harm in passing the error to the callback. I do see a lot of harm in throwing because it's going to bypass the error handling which users already have in place and crash their program instead. I would strongly object to that approach.

**Comment by arthurschreiber** [comment]
@bretcope I understand what you're aiming for.

But let me play Devil's advocate here. :wink:

That's not even how core Node.JS / io.js code works. If there is a check that can be made e.g. before an asynchronous function is executed and this check shows a programmer error (not an operational error), even node.js internal libraries will throw an exception. E.g. see here: https://github.com/iojs/io.js/blob/v1.x/lib/_http_client.js#L46-L57

Even the Joyent Best practices guide for error handling states:
> You should throw these [programmer] errors immediately, since the program is broken and the best chance of debugging it involves getting at least a stack trace and ideally a core file at the point of the error.

I'd definitely categorize non-matching types as a programmer error and not an operational error.

**Comment by bretcope** [comment]
I don't agree that this is necessarily programmer error. I think it's very likely to be an input validation problem which occurs dynamically.

I also don't see what problem is being solved by throwing versus passing the error to the callback. You can create the error synchronously which means you'll still get a good stack trace. Furthermore, it's non-obvious that it might throw, and if you do decide to wrap it in a try/catch, that means your function can't be optimized since v8 won't optimize any function with a try/catch anywhere inside it.

I think throwing would be a very very bad idea. I can't think of specifics, but I seem to recall Node core itself has been bitten a few times by throwing errors on async methods where it was assumed that all errors would flow into the callback... so I guess I don't consider that a good argument. If there is something that is truly, unquestionably programmer error, such as perhaps sending the wrong number or arguments, then I think throwing is okay. I'm strongly against it for input validation, though.

If others feel it's an absolute must, then I would flag it under an `earlyErrors` config option which people might turn on during local dev, but leave off in production. Not sure if the number of users who would use it justifies the added complexity or not.

**Comment by arthurschreiber** [comment]
@bretcope Thanks for the long reply. I don't care a lot about which direction we go here, anyway. I just wanted to point out that "not mixing error handling strategies" is not necessarily the only thing we should think about.

What I do care about is that we do not add too much arcane configuration options, so I'm definitely -1 on adding an error option for this.

Unless someone voices any more concerns, let's go with async error handling then.
