### ISSUE TITLE
Support for "Integrated Security" or "Trusted_Connection"

### ISSUE THREAD

**Issue by karthim** [pekim/tedious#306]
Hi,

First of all, thanks for adding windows authentication. Currently we have to set the windows login password in a plain text format. Do you have any plans to implement "Integrated Security" or "Trusted_Connection" i.e., automatically getting the currently logged-in user credentials. 

Regards,
Karthic

**Comment by mshenfield** [comment]
@karthim It looks like the only way to do this is to reference Windows C libs, see #134. I can't speak for the maintainers, but it seems like adding native dependencies would be a big shift for this lib. They've mentioned it as "non-trivial" a few times in previous issues (#207, #190).

Personally, I also came to this lib looking for "Trusted_Connection" support. Using environment variables or DSN files is a good alternative in the interim. And (silver lining) it makes client code less platform dependent.

I think clarifying this in the documentation would be a good step, since the issue has been raised a few times.

**Comment by arthurschreiber** [comment]
We definately don't want to add a binary component to tedious. One workaround would be to have a seperate node module that e.g. uses FFI to provide this functionality. But I currently don't have the time to create or maintain such a library.

**Comment by mshenfield** [comment]
I'm looking around at [pyodbc](https://github.com/mkleehammer/pyodbc) and [Azure/node-sqlserver](https://github.com/Azure/node-sqlserver) for some inspiration. They both basically proxy back to the Windows SQL driver to broker connections - but looking through the code I can see why you wouldn't be interested in maintaining something similar. I'm going to climb out of this rabbit hole for now.

**Comment by arthurschreiber** [comment]
I'm closing this for now, as it's not something that I believe we can implement with reasanoble effort. Feel free to re-open if you feel otherwise.
