### ISSUE TITLE
Query queueing

### ISSUE THREAD

**Issue by janmeier** [pekim/tedious#318]
Hi @pekim 

You might already have noticed us talking about https://github.com/pekim/tedious/issues/19 over in https://github.com/sequelize/sequelize/issues/4105

Basically node-pg and node-mysql allows you to send several queries on the same connection object - they are then queued in some way, since the actual connection only allows a single query at once, just like mssql (I haven't looked into how they actually implement this)

Ideally, we want to hide this implementation detail away from the sequelize users - specially when using transactions, where all queries are invoked in the same connection. Right now users have to manually wait for the first query to finish before executing the next one.

I'm just opening this issue here to ask whether you'd be open to implement some kind of query-queueing in tedious? In my view that would be the most ideal solution, otherwise we'd have to monkey-patch a solution in sequelize. I know @vesters might be interested in posting a bounty

**Comment by arthurschreiber** [comment]
How is that working with transactions in MySQL and PostgreSQL adapters?

**Comment by janmeier** [comment]
I've only looked at node-pg briefly, but here's my gist:

In `client.query`, the query is being added to a queue instead of being invoked directly and the queue is then pulsed [here](https://github.com/brianc/node-postgres/blob/3f32f7d8a68883aa4659c79bed9c53ff163a95e1/lib/client.js#L325-L326). What this means is that if the connection is ready for a query, the query is submitted, otherwise nothing happens [here](https://github.com/brianc/node-postgres/blob/3f32f7d8a68883aa4659c79bed9c53ff163a95e1/lib/client.js#L292-L304). Once a query ends, the connection emits `readyForQuery`, which pulses the queue again and submits the next query [here](https://github.com/brianc/node-postgres/blob/3f32f7d8a68883aa4659c79bed9c53ff163a95e1/lib/client.js#L157-L165)

**Comment by arthurschreiber** [comment]
So, here's my take on this. Adding this would be pretty easy. But educating users when and how to use this properly is going to be a pain. I can imagine people will go ahead and mix queries and transactions left and right, and then wondering why things break in unexpected ways. I definately remember an issue here where someone wanted to use a single tedious connection across different request handlers in express, and was suggesting query queuing as a solution (which is totally the wrong attempt at solving this). 

Also, @pekim is no longer actively developing tedious, the most active contributors are @bretcope, @patriksimek and me.

**Comment by janmeier** [comment]
It seems to work pretty well for mysql and postgres though? It wouldn't have to be limited to transactions only, it could be used for all queries, so you'd always be able to call `execSql` regardless of whether a query is currently running on the connection or not. 
I haven't looked closely at the tedious api yet though, do connections and transactions have separate objects? In any case I guess a transaction uses a connection under the hood so it would only need to be implemented at the connection level. 

I agree, using the same connection across multiple requests is very wrong, but that sounds like a complete misunderstanding of what a connection is :-D?

**Comment by arthurschreiber** [comment]
I wasn't thinking about limiting this to transactions. :)

Transactions are implemented using methods on the connection object. Again, as I said this would not be hard to implement inside tedious, but I'm still wary about adding this without having thought a bit about it.

@bretcope Any input from your side?

**Comment by bretcope** [comment]
I don't really have any specific thoughts on it. I would worry a lot about edge cases and ways that people could get confused.

**Comment by mikkelwf** [comment]
My two cents, seeing this from an end point user point of view, utilizing tedious through sequelize.

The reason me and @vesters originally raised this issue, is that our app utilize transactions when creating/updating items in the db. Its paramount for us that all actions are performed, or rolled back to the initial state, hence we use transactions. We started development on postgres, because its our natural devel environment, and everything worked as expected. When migrating to mssql, the transactions stopped working. Basically due to this issue.

I admit i'm not very much into the low level db stuff as you guys are, so you concerns about this feature would cause issues or confusion are totally valid points that should be discussed and resolved. But as i see it, the transactional model for mssql is broken right now due to the fact that tedious doesn't support query queing. At least its broken compared to postgres and mysql, where this is already possible. I find this to be a mayor issue, and very much limits the transactional model to only fetch data, not update. Thats a paramount concern for our project, and of cause we would like it to be resolved soon (that also why we would gladly support financially if it would ease the process).

**Comment by arthurschreiber** [comment]
@mikkelwf Thanks for your input. :heart: 

Allow me to point out that transaction support is working just fine in `tedious`, without query queuing.

There is 3 ways on how to use transactions right now:

* Using `tedious.Connection#transaction`, which transparently handles nested transactions (using savepoints) and does all the transaction commit and rollback handling automatically.
* Using `tedious.Connection#beginTransaction`, `tedious.Connection#commitTransaction` and `tedious.Connection#rollbackTransaction` manually, which does not support transaction nesting and involves more work.
* Executing queries containing `BEGIN TRANSACTION`, `COMMIT TRANSACTION`, `ROLLBACK TRANSACTION` instructions which is fully supported but not really recommended.

If you think these constructs don't work correctly, I'm happy for any bug reports. I'm personally using these successfully in a pretty large project, so I'd be surprised if they're really broken.

---

Now, back to `sequelize` and the issues you're having. From what I understand, `tedious` is already working fine with `sequelize` for the non-transactional case. Only when starting a transaction, `sequelize` is sometimes trying to execute a query while another query is already being executed by `tedious`. I'm not familiar with the `sequelize` codebase, but I'll promise to take a look into how this is working and then decide what approach to take.

Yes, query queueing might fix this problem with `sequelize`, but I'm not sure it's a good fix.

**Comment by janmeier** [comment]
@arthurschreiber Sequelize uses  `beginTransaction` etc, see https://github.com/sequelize/sequelize/blob/master/lib/dialects/mssql/query.js

The gist is that sequelize allows you to do:
```js
sequelize.transaction().then(function (t) {
  return Promise.all([
    A.findAll({ transaction: t }),
    B.findAll({ transaction: t })
  ]);
});
```
Two separate calls - normally outside a transaction they would use separate connections, but inside a transaction they use the same connection and try to simultaneously send the request, which gives an error. 

It could be fixed by the user by simply doing 
```js
sequelize.transaction().then(function (t) {
  return A.findAll({ transaction: t }).then(function () {
    B.findAll({ transaction: t })
  });
});
```
But that gives a feeling that the two must always happen sequentially, even though they don't have to. + it feels weird for the user to have to think about this in transactions but not outside - and only when using mssql

**Comment by arthurschreiber** [comment]
This looks to me like sequelize is the culprit.

In the example you've show, you use `Promise.all`, which gives the impression that the two promises are executed in parallel, while behind the scene, different things might happen:

* If sequelize is not executing a transaction, the queries get executed in parallel.
* If sequelize is executing a transaction, the queries get executed in serial.

This is _really_, _really_ weird.

In my opinion, the decision whether queries are executed in truly parallel or sequential fashion should be made by the user, and not by sequelize. This feels that it can lead to a lot of pain to understand what sequelize is doing, because what it's doing depends on the context in which it's executed. Especially because the performance profile will suddenly change when in a transaction.

If you want serial execution, your example should look like this:

```js
sequelize.transaction().then(function (t) {
  return Promise.each([
    A.findAll({ transaction: t }),
    B.findAll({ transaction: t })
  ]);
});
```

I'm sorry to say, but this feels like something is really off in the design of sequelize. :disappointed:

**Comment by janmeier** [comment]
My though was that the serialization of the queries doesn't matter to me - A before B is equally valid as B before A - So I just pretend, from the view of my code that they execute in parallel - I don't mind how sequelize serializes them.

I do kinda see your point though that it will always be semi-flawed abstraction in this case. However, the same thing might happen if there is only a single connection left in the connection pool - in that case the queries will be executed serially as well, but we hide that from the user as well. 
In general we try to hide all the connection stuff away from the user, so they can write queries without having to worry about the underlying connection(s).

I a transaction the queries will always execute in serial for obvious reasons, so the user would have no real choice - I'd rather look at it in the sense that with connection querying users won't have to worry about being inside a transaction or not - they can write queries that look parallel no matter what, how they are executed is up to sequelize.

Thanks for the good discussion and fast response. I guess will go the :monkey:-patching way ;)

**Comment by janmeier** [comment]
Oh, and thanks for a good library - apart from the weirdnesses of mssql syntax (which we can't really blame you for ;) ) its nice to work with

**Comment by nicholaswmin** [comment]
Hi people, reviving this since it might be connected to an issue I have with the mssql driver for Node.
I'm wondering, does the transaction queue wait for each query to respond before sending the next one? 

Would this [comment made here][1] apply for tedious for example?

[1]: https://github.com/tgriesser/knex/issues/1806#issuecomment-263315348
